/**
 * D-11 (RESEARCH §2, "RSC-root build-forbidden proof") — the machine assertion that
 * `edgerunner`'s Server-Component root NEVER pulls the heavy rich-lane chunk into the
 * RSC graph.
 *
 * The rich lane is TWO files (RESEARCH §2 / 13-PATTERNS):
 *   - `edgerunner/HoloShape.tsx` — the THIN `'use client'` mount; imports ONLY
 *     `next/dynamic` + React, and calls `dynamic(() => import('./Scene'), { ssr: false })`
 *     (allowed INSIDE a Client Component).
 *   - `edgerunner/Scene.tsx` — the HEAVY chunk (the ~235 kB the lazy import loads after
 *     paint); the ONLY file that imports `three` / `@react-three/*`.
 *
 * The RSC root `edgerunner/index.tsx` MUST import NEITHER `three` NOR `@react-three/*`,
 * and MUST NOT call `dynamic({ ssr: false })`. Next 16 hard-errors verbatim: "`ssr: false`
 * is not allowed with `next/dynamic` in Server Components. Please move it into a Client
 * Component." (CONTRACT.md §5; registry.ts:11-17). An accidental
 * `import { Canvas } from '@react-three/fiber'` in the root would also leak the heavy chunk
 * into First Load JS (D-05 / RESEARCH Pitfall 2). This grep is the loud guard.
 *
 * ── WHY A SOURCE-TEXT GREP (modeled on `security-grep.test.ts`) ────────────────────
 * Same idiom as the existing static template gates: read the source as text and assert the
 * forbidden pattern is absent. COMMENT HYGIENE is load-bearing — a documenting comment that
 * mentions `three` (e.g. "// the heavy three import lives in Scene.tsx") must NOT self-
 * invalidate the test, so comment lines are stripped before matching (only real
 * import/dynamic statements are considered).
 *
 * ── WHY SKIP-WHEN-ABSENT ──────────────────────────────────────────────────────────
 * `edgerunner/index.tsx` is generated by plan 04. Until then the test SKIPS with a clear
 * message rather than failing — it is a Wave-0 guard armed AHEAD of the file it protects, so
 * it must not be a spurious red while the folder holds only INGEST-MANIFEST.md. The moment
 * plan 04 writes the root, this test runs the three/R3F/ssr:false absence assertions.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const RSC_ROOT = path.resolve('src/components/templates/edgerunner/index.tsx');
const ROOT_EXISTS = existsSync(RSC_ROOT);

/**
 * Strip comment lines (line comments and block-comment body/open/close lines) so a comment
 * that legitimately MENTIONS `three` / `@react-three` / `ssr: false` (documenting the rule)
 * does not false-trip the grep. We only want to catch real import statements / dynamic calls.
 */
function stripComments(src: string): string {
  return src
    .split(/\r?\n/)
    .filter((line) => {
      const t = line.trim();
      return !(t.startsWith('//') || t.startsWith('*') || t.startsWith('/*') || t.startsWith('*/'));
    })
    .join('\n');
}

describe('D-11 — the edgerunner RSC root is build-forbidden from the rich-lane chunk', () => {
  it.skipIf(!ROOT_EXISTS)(
    'edgerunner/index.tsx does NOT import three / @react-three and does NOT call dynamic({ ssr:false })',
    () => {
      const code = stripComments(readFileSync(RSC_ROOT, 'utf8'));

      // No `import ... from 'three'` (bare specifier or a `three/...` subpath).
      expect(
        /import\s+[^;]*\bfrom\s+['"]three(?:\/[^'"]*)?['"]/.test(code),
        "edgerunner/index.tsx imports `three` — the WebGL engine MUST live one level down in " +
          "Scene.tsx (the lazy {ssr:false} chunk), never in the RSC root (D-11 / leaks heavy chunk into First Load JS).",
      ).toBe(false);

      // No `import ... from '@react-three/...'` (fiber / drei / anything under the scope).
      expect(
        /import\s+[^;]*\bfrom\s+['"]@react-three\/[^'"]+['"]/.test(code),
        "edgerunner/index.tsx imports `@react-three/*` — R3F/drei MUST live in Scene.tsx, never in " +
          'the RSC root (D-11).',
      ).toBe(false);

      // No `dynamic(...)` call combined with `ssr: false` / `ssr:false` — build-forbidden in a
      // Server Component (Next 16 hard-errors). The {ssr:false} mount belongs in the
      // 'use client' HoloShape.tsx, not the RSC root.
      const hasDynamicCall = /\bdynamic\s*\(/.test(code);
      const hasSsrFalse = /ssr\s*:\s*false/.test(code);
      expect(
        hasDynamicCall && hasSsrFalse,
        "edgerunner/index.tsx calls `dynamic(..., { ssr: false })` — that is build-forbidden in a " +
          "Server Component (Next 16: \"ssr: false is not allowed with next/dynamic in Server Components\"). " +
          'Move the {ssr:false} mount into the client HoloShape.tsx (D-11 / CONTRACT.md §5).',
      ).toBe(false);
    },
  );

  it.runIf(!ROOT_EXISTS)(
    'PENDING: edgerunner/index.tsx not yet generated (plan 04) — the D-11 grep activates the moment it exists',
    () => {
      // This is the "armed but waiting" marker so the suite is never empty/green-by-omission.
      // It asserts the precondition (folder present, root absent) so a stray early-written
      // root would flip THIS case red and the real assertions above would take over.
      expect(ROOT_EXISTS).toBe(false);
    },
  );
});
