-- seed.sql
-- Phase 1 (Security & Data Foundation) — Plan 01-08 — handoff T6 (dev seed)
--
-- Loaded automatically after migrations during `supabase db reset`
-- (config.toml: [db.seed] enabled = true, sql_paths = ["./seed.sql"]).
--
-- PURPOSE: local-development fixtures that the Layer-2 RLS integration suite
-- (Plan 01-09) can rely on. Per 01-RESEARCH.md Open Question 3 (RESOLVED), the
-- two RLS test users (A and B) are NOT seeded here — they are created at test
-- time by `tests/integration/_setup.ts` via `auth.admin.createUser(...)`, which
-- exercises the real `handle_new_user` trigger and confirmed email flow. Seeding
-- `auth.users` directly here would bypass that trigger and is therefore avoided.
--
-- IN-06: the `minimal` template is seeded by migration 001_initial_schema.sql
-- ITSELF (idempotently, `ON CONFLICT (slug) DO NOTHING`) because production must
-- have it and a portfolio cannot initialize without it. It was ALSO duplicated
-- here, copy-pasting the full `spec` JSON — two sources of truth that could
-- silently diverge if one was updated and not the other. The duplicate is
-- REMOVED: migration 001 is the single source of truth for the template spec.
--
-- The RLS integration suite's two test users (A and B) are NOT seeded here
-- either — they are created at test time by tests/integration/_setup.ts via
-- `auth.admin.createUser(...)`, which exercises the real `handle_new_user`
-- trigger (Open Question 3, RESOLVED). Seeding `auth.users` directly here would
-- bypass that trigger and is therefore avoided.
--
-- There are consequently NO seed-only fixtures left for the MVP. This file is
-- intentionally a no-op placeholder kept for [db.seed] wiring (config.toml) and
-- as the obvious home for any future local-only fixture.
